### ISSUE TITLE
how to use it in jsx?

### ISSUE THREAD

**Issue by OneKissAndOneShot** [soerenmartius/vue3-clipboard#93]
First of all, thank you very much for providing this wheel。

How to use it in jsx？

My project uses "vue": "^3.0.5"

**Comment by soerenmartius** [comment]
I don't work with TSX so I am not quite sure but I guess you can just import the standalone function?

**Comment by OneKissAndOneShot** [comment]
> I don't work with TSX so I am not quite sure but I guess you can just import the standalone function?

ok，i will try。thanks。
